### ISSUE TITLE
[아이템 1] 서비스 제공자 프레임워크 

### ISSUE THREAD

**Issue by grdnlee** [2021BookChallenge/Effective-Java#1]
정적 팩터리 메서드의 다섯번째 장점: 정적 팩터리 메서드를 작성하는 시점에는 반환할 객체의 클래스가 존재하지 않아도 된다.  
_이런 유연함은 서비스 제공자 프레임워크를 만드는 근간이 된다?_   

- ~동반 클래스~
- ~싱글톤 사용 이유~
- ~JDBC~
- ~브리지 패턴~
- ~의존 객체 주입 프레임 워크~

**Comment by sypark9646** [comment]
JDBC에서 `반환할 객체의 클래스가 존재하지 않아도 된다.` 이 부분은 조금 알아보긴 했는데 

일단 jdbc 실행 순서부터 보자면 아래 코드가 흔히  jdbc를 이용해서 db 커넥션을 만드는 코드잖아
```java
public static void main(String[] args) {
	String driverName = "com.mysql.jdbc.Driver";
	String url = "jdbc:mysql://localhost:3306/test";
	String user = "root";
	String password = "soyeon";
    
	try {
		Class.forName(driverName);

		// 서비스 접근 API인 DriverManager.getConnection가 서비스 구현체(서비스 인터페이스)인 Connection 반환
		Connection connection = DriverManager.getConnection(url, user, password);

	} catch (ClassNotFoundException e) {
		e.printStackTrace();
	} catch (SQLException e) {
		e.printStackTrace();
	}
}
```
그런데 이 코드에서 Class.forName으로 드라이버 이름만 호출했는데 => 이 부분에서 리플렉션
DriverManager가 mysql 드라이버임을 알고, 커넥션을 만들어서 리턴하는데

jdbc 실행 과정은 아래와 같고,
1. Class.forName(String name) 메소드에 의해 문자열로 전달되는 "com.mysql.jdbc.Driver"이라는 클래스가 메모리에 로드 된다.
2. Class.forName("com.mysql.jdbc.Driver") 실행시 JDBC Driver가 자동 등록된다.
    * [mysql jdbc driver code](http://www.docjar.com/html/api/com/mysql/jdbc/Driver.java.html): 여기 들어가보면 static 절 안에서 DriverManager.registerDriver() 메소드를 통해 자기 자신을 등록하는 부분이 있음. 근데 static은 메모리에 로드되면서 한번만 올라감
3. 등록한 JDBC Driver는 데이터베이스 Connection을 생성하는 시점에 사용되게 된다.

이렇게 JVM 동작 후에, main 코드가 실행되기 전까지는 어떤 JDBC 드라이버가 사용될 지 모르기 때문에, 
동적으로 드라이버를 로딩하기 위해 리플렉션(java.lang.reflect)을 이용한다고 합니당ㅋㅋㅋ

**Comment by grdnlee** [comment]
- 동반 클래스
<img width="1056" alt="스크린샷 2021-01-06 오후 8 24 43" src="https://user-images.githubusercontent.com/45806836/103763474-38cbe800-505d-11eb-9e81-dec5b43d7aa9.png">

**Comment by sypark9646** [comment]
싱글톤을 쓰는 이유
- 고정된 메모리 영역을 얻으면서 한번의 new로 인스턴스를 사용하기 때문에 메모리 낭비를 방지할 수 있음
- 싱글톤으로 만들어진 클래스의 인스턴스는 전역 인스턴스이기 때문에 다른 클래스의 인스턴스들이 데이터를 공유하기 쉽다.
ex) DBCP(DataBase Connection Pool)처럼 공통된 객체를 여러개 생성해서 사용해야하는 상황에서 많이 사용. (쓰레드풀, 캐시, 대화상자, 사용자 설정, 레지스트리 설정, 로그 기록 객체등)

ex) 안드로이드 앱 같은 경우는 각 액티비티나 클래스별로 주요 클래스들을 일일이 전달하기가 번거롭기 때문에 싱글톤 클래스를 만들어 어디서나 접근하도록 설계하는 것이 편함

- 인스턴스가 절대적으로 한개만 존재하는 것을 보증하고 싶을 경우 사용.
- 두 번째 이용시부터는 객체 로딩 시간이 현저하게 줄어 성능이 좋아지는 장점

* * *
단점으로는
싱글톤 인스턴스가 너무 많은 일을 하거나 많은 데이터를 공유시킬 경우 다른 클래스의 인스턴스들 간에 결합도가 높아져 `개방-폐쇄 원칙` 을 위배하게 돼 (=객체 지향 설계 원칙에 어긋남)

이렇게 되면 수정이 어려워지고 테스트하기 어려워진다.

그리고 멀티쓰레드환경에서 동기화처리를 안하면 인스턴스가 두개가 생성된다든지 하는 경우가 발생할 수 있음

마지막으로 lifecycle제어하기 힘들다는 점도 있다고 하넹,,,
예를들어 앱에 한 군데에서만 쓰고 말 모듈을 싱글톤으로 구현했을때, 해당 싱글톤이 제대로 gc가 되지 않는다면 끝까지 메모리를 차지하고 있다고 해

그래서 싱글톤의 경우도 꼭 필요한 경우아니면 지양해야 하나봐
