### ISSUE TITLE
[아이템 4] 인스턴스화

### ISSUE THREAD

**Issue by grdnlee** [2021BookChallenge/Effective-Java#4]
인스턴스화를 막는 이유는?

**Comment by grdnlee** [comment]
유틸리티 클래스는 메서드만 필요하니까.  
인터페이스로 만들기엔 상속해서 생성자 호출할 수도 있고
생성자로 인해 메모리 낭비가 발생할 수 있으니까?

**Comment by sypark9646** [comment]
XXXUtils와 같은 static 멤버만 있는 클래스는 굳이 new 키워드를 통해 의미없이 인스턴스화 할 필요가 없다
왜냐면 (1) 메모리만 낭비하기도 하고, (2) 다른 사용자가 오해해서 인스턴스화 해서 사용할 가능성이 있기 때문 
코드 가독성도 더 좋기도 하고...!!
