### ISSUE TITLE
[아이템1] 반환 타입의 하위 타입 객체를 반환할 수 있는 능력이 있다. - 인터페이스기반 프레임워크(아이템20)의 핵심기술

### ISSUE THREAD

**Issue by sypark9646** [2021BookChallenge/Effective-Java#5]
p.10 동반클래스?
```text
자바 8 전에는 인터페이스에 정적 메서드를 선언할 수 없었다. 
그렇기 때문 에 이름이 “Type”인 인터페이스를 반환하는 정적 메서드가 필요하면, 
“Types” 라는 （인스턴스화 불가인） 동반 클래스（companion class）를 만들어 그 안에 정 의하는 것이 관례였다. 
예컨대 자바 컬렉션 프레임워크는 핵심 인터페이스들 에 수정 불가나 동기화 등의 기능을 덧붙인 총 45개의 유틸리티 구현체를 제공 하는데, 
이 구현체 대부분을 단 하나의 인스턴스화 불가 클래스인 java.util. Collections에서 정적 팩터 리 메서드를 통해 얻도록 했다.
```
```text
자바 8부터는 인터페이스가 정적 메서드를 가질 수 없다는 제한이 풀렸기 때 문에 인스턴스화 불가 동반 클래스를 둘 이유가 별로 없다. 
동반 클래스에 두었던 public 정적 멤버들 상당수를 그냥 인터페이스 자체에 두면 되는 것이다. 
하지만 정적 메서드들을 구현하기 위한 코드 중 많은 부분은 여전히 별도의 package-private 클래스에 두어야 할 수 있다. 
자바 8에서도 인터페이스에는 public 정적 멤버만 허용하기 때문이다. 
자바 9에서는 private 정적 메서드까지 허락하지만 정적 필드와 정적 멤버 클래스는 여전히 public이어야 한다.
```

**Comment by grdnlee** [comment]
**반환할 객체의 클래스를 자유롭게 선택할 수 있는 '유연성'을 부여해준다.**

정적 메서드로부터 인터페이스 자체를 반환하여, 구현 클래스를 공개하지 않고도 그 객체를 반환할 수 있다.  
구현 클래스의 상세를 숨길 수 있고, 사용자는 객체를 인터페이스만으로 다룰 수 있다.

클래스에서 만들어 줄 객체의 클래스를 선택하는 유연함이 있다. 리턴타입의 하위 타입인 인스턴스를 만들어줘도 되니까, 리턴 타입은 인터페이스로 지정하고 구현 클래스를 API에 노출시키지 않고도 그 객체를 반환할 수 있어, API를 작게 유지할 수 있다. 이는 인터페이스를 정적 팩토리 메서드의 반환 타입으로 사용하는 **인터페이스 기반 프레임워크**를 만드는 핵심 기술이기도 하다.

리턴 타입엔 인터페이스만 노출, 실제 리턴하는 객체는 인터페이스의 구현체를 리턴하는 것.  
→ 밖에서 보는 클라이언트 입장에선 인터페이스만 가지고 코딩, 실제 구현체는 모름.

이 예로 `java.util.Collections`가 있다.  
프로그래머는 명시한 인터페이스대로 동작하는 객체를 얻을 것임을 알기에 굳이 별도 문서를 찾아가며 실제 구현 클래스가 무엇인지 알아보지 않아도 된다. 나아가 정적 팩토리 메서드를 사용하는 클라이언트는 얻은 객체를 (그 구현 클래스가 아닌) 인터페이스만으로 다루게 된다.
