### ISSUE TITLE
[아이템 10] 비교하기 복잡한 필드를 가진 클래스의 비교 방법 

### ISSUE THREAD

**Issue by grdnlee** [2021BookChallenge/Effective-Java#7]
(p. 63)

필드의 표준형을 저장해둔 후 표준형끼리 비교하면 훨씬 경제적이다?

이 기법은 특히 불변 클래스에 제격이다?

**Comment by sypark9646** [comment]
effective java 예제에서 말하는건 이렇게 equals할 때마다 객체를 upper로 바꿔서 비교하면 비용이 드니까,
미리 객체를 만들 때 이걸 비교할 때 쓰는 `표준형`을 저장해 두면 비교연산에서는 이 표준형만 비교하게 되는거지

```java
public final class CaseInsensitiveString {

  private final String s;
  private final String sForEquals; //equals를 단순화 하기 위한 필드

  public CaseInsensitiveString(String s) {
      if (s == null) {
          throw new IllegalArgumentException(); //NullPointerException()
      }
      this.s = s;
      this.sForEquals = s.toUpperCase(); //upper 또는 lower로 초기화
  }

  @Override
  public boolean equals(Object o) {
      return o instanceof CaseInsensitiveString &&
          ((CaseInsensitiveString) o).sForEquals.equals(this.sForEquals);
  }

  @Override
  public int hashCode(){
      return sForEquals.hashCode();
  }
  // remainder omitted
}
```

https://stackoverflow.com/a/24428722/11285469 나는 여기 보고 좀 도움이 됐어!!

알고리즘 문제에서 구간 합을 자주 구할 때, segment tree를 사용하는 이유랑 뭔가 비슷한 것 같다ㅋㅋㅋ

**Comment by sypark9646** [comment]
불변 클래스는 나도 아직 공부가 덜 되어서 좀 더 알아보고 댓글 달게ㅠㅠ

**Comment by sypark9646** [comment]
불변클래스의 경우 값이 안바뀌니까 equals가 한번 같다고 한 객체와는 영원히 같다고 답하고, 
다르다고 한 객체와는 영원히 다르다고 답하도록 만들어야 한다.
=> 표준형이 자주 안바뀌니까 더 효과적이다.
